# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ce0c5bb3e73d0775df6d0c766b7f2d1e1c5ddb19cbda174939c2e4979395da33b2fb72f009e414f04d2af218ac7ed3b578b3e0acb3ffc86d86ecde87ac7bc6e

test:
  secret_key_base: 7ecc8efbd6e46f1734428816dd5e69732ce7bc05188475af6bb12086ab5bf5db72c90205f5fc69c638aa87d6f07efcc6870225bb6506e5a3f03f806811493013

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
